"""empty message

Revision ID: 28fd29ca8fb9
Revises: 7ac8d7c2efbf
Create Date: 2016-08-16 19:03:33.417532

"""

# revision identifiers, used by Alembic.
revision = '28fd29ca8fb9'
down_revision = '7ac8d7c2efbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
