"""empty message

Revision ID: 7ac8d7c2efbf
Revises: None
Create Date: 2016-08-16 17:42:46.256078

"""

# revision identifiers, used by Alembic.
revision = '7ac8d7c2efbf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('type_1', sa.Text(), nullable=True),
    sa.Column('type_2', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    ### end Alembic commands ###
